### PR TITLE
Upgrade to hijackresponse 5

### PR DESCRIPTION
**Pull request by gustavnikolaj**
Using the proposed api from: https://github.com/gustavnikolaj/hijackresponse/pull/24

### CODE REVIEW

**Comment by gustavnikolaj** [comment]
The latest commit updates to the first pre-release of v5. It also removes the err argument to the callback.

**Comment by papandreou** [comment]
This is nice -- happy to merge it once the api is finalized and 5.0.0 is released!

**Comment by gustavnikolaj** [comment]
This PR is ready for merge and release :-)

**Comment by papandreou** [comment]
Released in 3.1.0

**Pull request merged**
